query inventoryByProduct($_eq: String = "", $limit: Int = 10, $offset: Int = 0) {
  inventory(where: {p_code: {_eq: $_eq}}, limit: $limit, offset: $offset) {
    id
    product {
      added_by
      code
      name
    }
    count
    createdAt
  }
  total: inventory_aggregate {
    aggregate {
      count
    }
  }
}