query transactionbyshop($_eq: uuid = "") {
  sales(where: {shop: {_eq: $_eq}}) {
    id
    org
    shop
    role_id
    updatedAt
    createdAt
    transactions {
      id
      count
      product {
        amount
      }
    }
    active_role {
      userByUser {
        name
      }
    }
  }
}
