version: '3.6'

services:
  graphql-engine:
      image: hasura/graphql-engine:latest
      ports:
      - "8080:8080"
      restart: always
      environment:
        HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@db
        HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
        ## uncomment next line to set an admin secret
        HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
        HASURA_GRAPHQL_AUTH_HOOK: http://host.docker.internal:3001/auth/login/v2
        HASURA_GRAPHQL_AUTH_HOOK_MODE: POST
      extra_hosts:
        - "host.docker.internal:172.17.0.1"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql
  
volumes:
  db_data: