mutation addproduct($objects: [products_insert_input!] = {}) {
  insert_products(objects: $objects) {
    affected_rows
    returning {
      code
      amount
      createdAt
      id
      name
      org
      updatedAt
    }
  }
}

query findProductByCode($_eq: String = "") {
  products(where: {code: {_eq: $_eq}}) {
    code
    amount
    createdAt
    name
  }
}
