mutation addproduct(
  $name: String = ""
  $inventories: inventory_arr_rel_insert_input = { data: { count: 10 } }
  $code: String = ""
  $amount: numeric = ""
  $cost_price: numeric = ""
) {
  insert_products(
    objects: {
      amount: $amount
      code: $code
      name: $name
      inventories: $inventories
      cost_price: $cost_price
    }
  ) {
    affected_rows
    returning {
      code
      amount
      createdAt
      id
      name
      org
      updatedAt
    }
  }
}

query findProductByCode($_eq: String = "") {
  products(where: { code: { _eq: $_eq } }) {
    code
    amount
    createdAt
    name
    id
    cost_price
  }
}

mutation updateProduct($_set: products_set_input = {}, $id: uuid = "") {
  update_products_by_pk(pk_columns: { id: $id }, _set: $_set) {
    ...productsFragment
  }
}

fragment productsFragment on products {
  amount
  code
  id
  name
}
