query transactionbyshop($_eq: uuid = "", $limit: Int = 10, $offset: Int = 0, $_eq1: uuid = "") {
  sales(where: {shop: {_eq: $_eq}}, limit: $limit, offset: $offset, order_by: {createdAt: desc}) {
    id
    org
    shop
    role_id
    updatedAt
    createdAt
    active_role {
      userByUser {
        name
      }
    }
    transactions {
      id
      count
      price
      product {
        amount
        name
        cost_price
      }
    }
  }
  sales_aggregate(where: {shop: {_eq: $_eq}}) {
    aggregate {
      count
    }
  }
}


query getTotalByShops($limit: Int = 10) {
  total_sales_by_shop(limit: $limit) {
    total
    shop_name
    org
  }
}



query getSalesByDate($limit: Int = 10, $offset: Int = 0, $_eq: uuid = "") {
  shop_sales_by_date(limit: $limit, offset: $offset, order_by: {date: desc}, where: {id: {_eq: $_eq}}, distinct_on: date) {
    ...shop_sales_by_dateFragment
  }
  shop_sales_by_date_aggregate {
    aggregate {
      count(columns: date)
    }
  }
}

fragment shop_sales_by_dateFragment on shop_sales_by_date {
  date
  id
  shop_name
  total
}


query productSalesByShop {
  shops {
    products_sold(order_by: {amount: desc}) {
      amount
      name
    }
    id
    name
  }
}


