query yearlySales {
  yearly_sales {
    name
    org
    shop
    total
    yearly
  }
}


query weeklySales {
  weekly_sales {
    org
    shop
    total
    weekly
    name
  }
}


query monthlySales {
  monthly_sales {
    name
    org
    shop
    total
    weekly
  }
}

query top5ProductsDaily($limit: Int = 5) {
  top_products_daily(limit: $limit) {
    daily
    name
    org
    p_code
    sum
  }
}

