query yearlySales($_lte: timestamptz = "", $_gte: timestamptz = "", $_in: [uuid!] = "") {
  yearly_sales(where: {yearly: {_lte: $_lte, _gte: $_gte}, shop: {_in: $_in}}) {
    name
    org
    shop
    total
    yearly
    total_cost
  }
}




query weeklySales($_gte: timestamptz = "", $_lte: timestamptz = "", $_in: [uuid!] = "") {
  weekly_sales(where: {weekly: {_gte: $_gte, _lte: $_lte}, shop: {_in: $_in}}) {
    org
    shop
    total
    weekly
    name
    total_cost
  }
}


query monthlySales($_gte: timestamptz = "", $_lte: timestamptz = "", $_in: [uuid!] = "", $limit: Int = 1000) {
  monthly_sales(where: {monthly: {_gte: $_gte, _lte: $_lte}, shop: {_in: $_in}}, limit: $limit) {
    name
    org
    shop
    total
    monthly
    total_cost
  }
}


query dailySales($_gte: timestamptz = "", $_lte: timestamptz = "", $_in: [uuid!] = "") {
  daily_sales(where: {daily: {_gte: $_gte, _lte: $_lte}, shop: {_in: $_in}}) {
    name
    org
    shop
    total
    daily
    total_cost
  }
}



query top5ProductsDaily($limit: Int = 5, $_gte: timestamptz = "", $_lte: timestamptz = "") {
  top_products_daily(limit: $limit, where: {daily: {_gte: $_gte, _lte: $_lte}}) {
    daily
    name
    org
    p_code
    sum
  }
}



query lowInventoryProducts($limit: Int = 10) {
  products_in_store(order_by: {total_products: desc}, limit: $limit) {
    name
    org
    total_products
  }
}
