query yearlySales($_lte: timestamptz = "", $_gte: timestamptz = "") {
  yearly_sales(where: {yearly: {_lte: $_lte, _gte: $_gte}, shop: {}}) {
    name
    org
    shop
    total
    yearly
  }
}



query weeklySales($_gte: timestamptz = "", $_lte: timestamptz = "") {
  weekly_sales(where: {weekly: {_gte: $_gte, _lte: $_lte}}) {
    org
    shop
    total
    weekly
    name
  }
}


query monthlySales($_gte: timestamptz = "", $_lte: timestamptz = "") {
  monthly_sales(where: {monthly: {_gte: $_gte, _lte: $_lte}}) {
    name
    org
    shop
    total
    monthly
  }
}


query top5ProductsDaily($limit: Int = 5) {
  top_products_daily(limit: $limit) {
    daily
    name
    org
    p_code
    sum
  }
}


query lowInventoryProducts($limit: Int = 10) {
  products_in_store(order_by: {total_products: desc}, limit: $limit) {
    name
    org
    total_products
  }
}
