version: '3.6'

services:
  hasura:
    image: postgres
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: postgres
    ports:
    - "5432:5432"
    networks:
    - postgres
  graphql-engine:
    image: hasura/graphql-engine:v2.0.0-alpha.9
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:XBURkwBwtghjEru7dYbB@database-1.coal1dztexb4.ap-south-1.rds.amazonaws.com:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_AUTH_HOOK: http://host.docker.internal:8082/auth/login/v2
      HASURA_GRAPHQL_AUTH_HOOK_MODE: POST
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-postgres}
      PGADMIN_CONFIG_SERVER_MODE: 'True'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
volumes:
  db_data:
networks:
  postgres:
    name: postgres