query getusers {
    users{
      name
    }
  }

query getproducts($_iregex: String = "", $limit: Int = 10, $offset: Int = 0) {
  products(limit: $limit, offset: $offset, where: {name: {_iregex: $_iregex}}) {
    amount
    code
    createdAt
    id
    name
    org
  }
}

  