query getinventory($limit: Int = 10, $offset: Int = 10, $_iregex: String = "", $_iregex1: String = "") {
  products_left_in_store(limit: $limit, offset: $offset, where: {_or: {product: {name: {_iregex: $_iregex}}, p_code: {_iregex: $_iregex1}}}) {
    org
    p_code
    total
    sold
    product {
      amount
      code
      createdAt
      id
      added_by
      name
    }
  }
}



mutation addinventory($object: inventory_insert_input = {}) {
  insert_inventory_one(object: $object) {
    count
    createdAt
    id
    p_code
    updatedAt
  }
}
