query getinventory($limit: Int = 10, $offset: Int = 10, $_iregex: String = "", $_iregex1: String = "") {
  products_in_store(where: {_or: {p_code: {_iregex: $_iregex}, name: {_iregex: $_iregex1}}}) {
    sold_products {
      amount
      sold
    }
    org
    p_code
    name
    total_products
  }
}



mutation addinventory($object: inventory_insert_input = {}) {
  insert_inventory_one(object: $object) {
    count
    createdAt
    id
    p_code
    updatedAt
  }
}
